# .goreleaser.yaml
# Build configuration for Samsa

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/samsa/main.go
    binary: samsa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/albertopastormr/samsa/internal/cli.version={{.Version}} -X github.com/albertopastormr/samsa/internal/cli.commit={{.Commit}} -X github.com/albertopastormr/samsa/internal/cli.date={{.Date}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
